global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - '/etc/prometheus/rules/rules.yml'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'fastapi_app'
    static_configs:
      - targets:
          - 'fastapi_app:8000'
          # - 'host.docker.internal:8000'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
