services:
  node-exporter:
    container_name: node-exporter
    ports:
      - 9100:9100
    image: prom/node-exporter
    volumes:
      - 'C:\:/host:ro'
    command:
      - '--path.rootfs=/host'
    # network_mode: host
    # netstat on win: --
    networks:
      - promet

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - '.\prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # network_mode: host
    networks:
      - promet
networks:
  promet:
    external: true
    name: promet_test
