services:
  prometheus-top:
    container_name: prometheus-top
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - './prometheus-top.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  prometheus-low:
    container_name: prometheus-low
    image: prom/prometheus
    ports:
      - 9091:9090
    volumes:
      - './prometheus-low.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
