services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - '.\server.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - promet

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    depends_on:
      - nginx
    ports:
      - 9113:9113
    command:
      - '--nginx.scrape-uri=http://nginx:80/stub_status'
    networks:
      - promet

networks:
  promet:
    # driver: bridge
    external: true
    name: promet_test
  