global:
  scrape_interval: 15s
  scrape_timeout: 10s


scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'

    relabel_configs:
      - source_labels: [__address__]
        regex: (.*):(.*)
        replacement: $2
        target_label: port
      - source_labels: [__address__]
        regex: (.*):(.*)
        replacement: $1
        target_label: host
      - target_label: additional
        replacement: extra_label_val
