global:
  scrape_interval: 15s
  scrape_timeout: 10s
      
scrape_configs:
  - job_name: 'file-sd'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets.json'
        refresh_interval: 5s

  # - job_name: 'docker-sd'
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock # Docker daemon API

  #   # relabel_configs:
  #   #   - source_labels: [__meta_docker_container_id]
  #   #     target_label: container_id
  #   #   - source_labels: [__meta_docker_container_name]
  #   #     target_label: container_name
